config/routes.rb
Rails.application.routes.draw do

      resources :fossevents

end

app/models/fossevent.rb
class Fossevent < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fossevents_controller.rb
class FosseventsController < ApplicationController
	def index
		@events = Fossevent.all
	end

	def new
		@event = Fossevent.new
	end

	def create
		Fossevent.create(create_params)
		redirect_to action: 'index'
	end

	def show 
	    # render html: "hkhkj"
	    @event =Fossevent.find(params[:id])

    end 


	private
	def create_params
		params.require(:fossevent).permit(:title, :from_date, :to_date, :event_type)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fossevents/index.html.erb
<div>
	<% @events.each do |event| %>
		<div>
			<%= event.title %>
			<%= event.from_date %>
			<%= event.to_date %>
			<%= event.event_type %>
			<%=link_to "Details", fossevent_path(event) %>
		</div>
	<% end %>
</div>

app/views/fossevents/new.html.erb
<%= form_for @event, url: {action: "create"} do |f| %>
	
	<div>
 		<label>Create Foss Event</label>
	</div>
	<br/>
	<div>
		<%= f.label :title %>
		<%= f.text_field :title,size:50 %> 
    </div>
    <br/>
        <div>
        	<fieldset>
           <legend>Eventdate</legend>        	
           <%= f.label :from_date %>
		   <%=f.date_field  :from_date %> 		   
		    <%= f.label :to_date %>
		   <%=f.date_field :to_date %> 
		   </fieldset>
	    </div>
   		<div>
         <%=f.label :event_type %><br/>
         <select name="fossevent[event_type]" id="f5" multiple=multiple>
            <option value="conference">Conference</option>
            <option value="hackathon">Hackathon</option>
            <option value="unconference">Unconference</option>
               <option value="meetup">Meetup</option>
               <option value="workshop">Workshop</option>
               <option value="tech-fest">tech-fest</option>
            </select >
   		</div><br/>
   		   <%=f.label :description %><br/>
           <%=f.text_area :description,:size => "30x10" %>
<br/>
<%=f.submit "Submit Event" %>

<% end %>

app/views/fossevents/show.html.erb
<div>
			<%= @event.title %>
			<%= @event.from_date %>
			<%= @event.to_date %>
			<%= @event.event_type %>
			<%=@event.description %>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fossevents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>